# Generated by Django 5.1.7 on 2025-03-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
