# Generated by Django 5.1.7 on 2025-03-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_issuedbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Non Returned', 'Non Returned')], max_length=15),
        ),
    ]
